### ISSUE TITLE
Unable to run code

### ISSUE THREAD

**Issue by zzyycc7** [zyqz97/GP-NeRF#4]
Hi, thanks for your great work! When I try to run your code, I encounter the following problem. Could you mind tell me how to fix it?

Traceback (most recent call last):
  File "gp_nerf/train.py", line 35, in <module>
    main(_get_train_opts())
  File "/home/zyc/anaconda3/envs/k-planes/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "gp_nerf/train.py", line 21, in main
    from gp_nerf.runner_gpnerf import Runner
  File "/home/zyc/Desktop/GP-NeRF-main/./gp_nerf/runner_gpnerf.py", line 28, in <module>
    from mega_nerf.datasets.filesystem_dataset import FilesystemDataset
  File "/home/zyc/Desktop/GP-NeRF-main/./mega_nerf/datasets/filesystem_dataset.py", line 24, in <module>
    class FilesystemDataset(Dataset):
  File "/home/zyc/Desktop/GP-NeRF-main/./mega_nerf/datasets/filesystem_dataset.py", line 310, in FilesystemDataset
    img_indices_dtype,desired_chunks=1000) -> List[Future[None]]:
TypeError: 'type' object is not subscriptable

**Comment by Dongber** [comment]
Hello, I'm having the same issue. How did you solve it?

**Comment by R-QinQ** [comment]
> Hello, I'm having the same issue. How did you solve it?
hello，How did you solve it?
